books = [
  {
    id: 1,
    author: "Chinua Achebe",
    country: "Nigeria",
    imageLink: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKibQ5NSwEZO1E2uv3YxkPFNhOjuANIgbNMA&usqp=CAU",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
    pages: 40,
    title: "Things Fall Apart",
    year: 1958,
    price: 60,
  },
  {
    id: 2,

    author: "Hans Christian Andersen",
    country: "Denmark",
    imageLink: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdCEVPp69YNoRFqO-aMXSqw3OjMjiT2u7FqQ&usqp=CAU",
    language: "Danish",
    link: "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
    pages: 50,
    title: "Fairy tales",
    year: 1836,
    price: 50,
  },
  {
    id: 3,

    author: "Dante Alighieri",
    country: "Italy",
    imageLink: "https://images-na.ssl-images-amazon.com/images/I/413UVUjPYFL.jpg",
    language: "Italian",
    link: "https://en.wikipedia.org/wiki/Divine_Comedy\n",
    pages: 92,
    title: "The Divine Comedy",
    year: 1315,
    price: 30,
  },
  {
    id: 4,

    author: "Unknown",
    country: "Sumer and Akkadian Empire",
    imageLink: "https://www.adobe.com/express/create/cover/media_178ebed46ae02d6f3284c7886e9b28c5bb9046a02.jpeg?width=400&format=jpeg&optimize=medium",
    language: "Akkadian",
    link: "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n",
    pages: 60,
    title: "The Epic Of Gilgamesh",
    year: -1700,
    price: 40,
  },
  {
    id: 5,

    author: "Unknown",
    country: "Achaemenid Empire",
    imageLink: "https://static01.nyt.com/images/2021/11/30/books/30TenBest-02/30TenBest-02-mobileMasterAt3x.jpg",
    language: "Hebrew",
    link: "https://en.wikipedia.org/wiki/Book_of_Job\n",
    pages: 70,
    title: "The Book Of Job",
    year: -600,
    price: 90,
  },
  {
    id: 6,

    author: "Unknown",
    country: "India/Iran/Iraq/Egypt/Tajikistan",
    imageLink: "https://edit.org/photos/images/cat/book-covers-big-2019101610.jpg-1300.jpg",
    language: "Arabic",
    link: "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
    pages: 28,
    title: "One Thousand and One Nights",
    year: 1200,
    price: 60,
  },
  {
    id: 7,

    author: "Unknown",
    country: "Iceland",
    imageLink: "https://www.penguin.co.uk/content/dam/prh/books/144/1443214/9780857527738.jpg.transform/PRHDesktopWide_small/image.jpg",
    language: "Old Norse",
    link: "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga\n",
    pages: 34,
    title: "Nj\u00e1l's Saga",
    year: 1350,
    price: 80,
  },
  {
    id: 8,

    author: "Jane Austen",
    country: "United Kingdom",
    imageLink: "https://www.adobe.com/express/create/cover/media_1b7327f720408f3da750167464f8cbcd74fa319c5.jpeg?width=400&format=jpeg&optimize=medium",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
    pages: 100,
    title: "Pride and Prejudice",
    year: 1813,
    price: 30,
  },
];
